### PR TITLE
Rusty JSC developments

### PR DESCRIPTION
**Pull request by adrien-zinger**
This PR includes a few enhancements to meet my expectations. Now I can set callbacks with arguments like:

```rust
#[callback]
fn log(context: JSContext, _function: JSObject, _this: JSObject, arguments: Vec<JSValue>) {
    arguments.iter().for_each(|value| {
        if value.is_string(&context) {
            println!("{}", value.to_string(&context));
        }
        // I also have added is_date and is_symbol
        if value.is_date(&context) {
            println!("date inthere!")
        }
    });
}
```

Parameters of callback functions follow a fall-through rule, 1 parameter = { context }, 2 = { context, function }, etc. But callbacks can also optionally return a JSValue, so I can define an identity function or anything similar.

```rust
#[callback]
fn echo(
    context: JSContext,
    _function: JSObject,
    _this: JSObject,
    arguments: Vec<JSValue>,
) -> JSValue {
    if let Some(argument) = arguments.first() {
        argument.clone()
    } else {
        JSValue::string(&context, "").unwrap()
    }
}
```

I can define a class with an internal function and write the constructor like we used to do with callbacks. The constructor definition can have up to 3 arguments corresponding to { context, this, arguments }. Then, with the resulting object, I could set parameters dynamically.

```rust
#[constructor]
fn constructor() {
    println!("into the user obj cnstructor");
}

let user_obj = JSObject::class(&context, "UserObject", Some(constructor));
```

The current PR contains several modifications, here is a list of all that we can find:

* add constructor macro
* macros can get multiple arguments
* callback macro can return a JSValue
* add .lock file in repository
* fixing .gitignore files in sys and macros
* add is_date and is_symbol
* add internal documentation only for JSObjectMake
* JSValue can be cloned (to review)
* JSValue and JSObject can be converted into each other
* JSObject can create a class
* JSValue implements to/into utf8 internally
* JSValue and JSObject implement a getter for the inner reference
* Static functions of JSValue and JSObject take any type that implements ToString instead of a String

### CODE REVIEW

**Comment by syrusakbary** [comment]
Hey @adrien-zinger , we are working already on a new branch that supports callbacks (and callback closures) fully.

Stay tuned!

**Comment by penberg** [comment]
Hey @adrien-zinger, thanks for doing this! There's a bigger pull request coming from @syrusakbary. Happy to work with you on getting any remaining bits in this pull request merged once @syrusakbary's PR lands in `main`.

**Comment by syrusakbary** [comment]
Here we go.
Feel free to review the big PR and provide feedback: #9

**Comment by adrien-zinger** [comment]
I have added also some management of retained objects (like classes and protected values) that allow to store and send values like callbacks with more security. The new version contains also the possibility to create promises.

**Comment by syrusakbary** [comment]
Hey @adrien-zinger if you want to rebase your changes on top of master now would be a great time!

**Comment by adrien-zinger** [comment]
> Hey @adrien-zinger if you want to rebase your changes on top of master now would be a great time!

Thank you @syrusakbary.

**Comment by syrusakbary** [comment]
Also, we need some automated tests on Github CI... any help there would be greatly appreciated!

**Comment by syrusakbary** [comment]
Note: the callbacks now accept variable arguments and can return a `Result<JSValue, JSValue>`. Please check the callbacks examples!

**Review by syrusakbary — APPROVED** [review]

**Comment by syrusakbary** [comment]
Apologizes for taking so long to review @adrien-zinger, but completely forgot and just stumbled upon the PR again (feel free to ping me on other PRs)

**Pull request merged**
